<meta name="description" content="Version 3.0 del glosario generado autom&aacute;ticamente">
<meta name="author" content="Glosarizador InMemoriAn">
<link rel="icon" href="media/favicon.gif" type="image/x-icon"/>
 <!--[if lt IE 9]>
 <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
<link rel="shortcut icon" href="media/favicon.gif" type="image/x-icon"/> 
<link rel="stylesheet" type="text/css" href="css/styles.css"/>
</head>
<body>
   <div class="bg">
    <!--start container-->
    <div id="container">
    <!--start header-->
    <header>
      <!--start logo-->
      <a href="#" id="logo"><img src="media/logo.png" width="180" height="180" alt="logo"/></a>    
      <!--end logo-->
      <!--start menu-->
      <nav>
         <ul>
         <li><h3>InMemoriAn: Ingenier&iacute;a Lingu&iacute;stica de la Memoria Cultural Andina</h3></li>
         <li><h3>Proyecto FONACIT 2012000099 Venezuela 2013-2016</h3></li>
         <li><h1>Diccionario de Ecocultura del P&aacute;ramo Andino de M&eacute;rida</h1></li> 
	 </ul>
         <ul>
         <li><a href="index.html" class="current">Principal</a></li>
         <li><a href="proyecto.html">Sobre el Proyecto</a></li>
         <li><a href="Creative Commons Legal Code.html">Licencia</a></li>
         <!--
     	   <li><a href="#">Services</a></li>
     	   <li><a href="#">Portfolio</a></li>
         <li><a href="#">News</a></li>
         -->
         <li><a href="creditos.html">Contactos</a></li>
         </ul>   
      </nav>
  	   <!--end menu-->
      <!--end header-->
	</header>
  <div class="holder_content">
      <section class="group1">
      <p>Este diccionario es una selecci&oacute;n autom&aacute;tica de textos a partir del corpus generado por un equipo de transcriptores de una serie de entrevistas a vecinos del p&aacute;ramo andino meride&ntilde;o</p>
      </hgroup>
   </section>

