<!doctype html>
<html lang="es">
<head>
<meta charset="UTF-8">
<title>InMemoriAN: Diccionario de Ecocultura del P&aacute;ramo Andino de M&eacute;rida - Bienvenid@s</title>
<meta name="description" content="Sitio Web del InMemoriAn y ULAnux">
<meta name="author" content="Jacinto Davila">
<link rel="icon" href="media/favicon.gif" type="image/x-icon"/>
 <!--[if lt IE 9]>
 <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
<link rel="shortcut icon" href="media/favicon.gif" type="image/x-icon"/> 
<link rel="stylesheet" type="text/css" href="css/styles.css"/>
</head>
<body>
   <div class="bg">
    <!--start container-->
    <div id="container">
    <!--start header-->
    <header>
      <!--start logo-->
      <a href="#" id="logo"><img src="media/logo.png" width="220" height="180" alt="logo"/></a>    
      <!--end logo-->
      <!--start menu-->
      <nav>
         <ul>
         <li><h3>InMemoriAn: Ingenier&iacute;a Lingu&iacute;stica de la Memoria Cultural Andina: - Bienvenid@s</h3></li>
         <li><h3>CESIMO, ULA, Proyecto FONACIT 2012000099 Venezuela 2013-2016</h3></li>
         <li><h1>Diccionario de Ecocultura del P&aacute;ramo Andino de M&eacute;rida</h1></li> 
	 </ul>
         <ul>
         <li><a href="./inmemorian/index.html" class="current">Principal</a></li>
         <li><a href="./inmemorian/proyecto.html">Sobre el Proyecto</a></li>
         <li><a href="./inmemorian/Creative Commons Legal Code.html">Licencia</a></li>
         <!--
     	   <li><a href="#">Services</a></li>
     	   <li><a href="#">Portfolio</a></li>
         <li><a href="#">News</a></li>
         -->
         <li><a href="./inmemorian/creditos.html">Contactos</a></li>
         </ul>   
      </nav>
  	   <!--end menu-->
      <!--end header-->
	</header>
<!-- body lang="en-US" vlink="#0000ff" dir="ltr"-->

   <!--start holder-->
   <div class="holder_content">
      <section class="group1">
<h1 align="justify">Bienvenidas y Bienvenidos a <font size="4" style="font-size: 16pt"><a href="http://nux.ula.ve/">http://nux.ula.ve</a>
(o <a href="http://ches.ing.ula.ve/">http://ches.ing.ula.ve</a>)</font></h1>

<p align="justify">Este es un Repositorio de Conocimiento Libre, instalado en La Universidad de Los Andes, Venezuela, por cortesía del Proyecto <b>InMemoriAn</b>, financiado por el Ministerio del Poder Popular para Ciencia, Tecnología e Innovación, de la República Bolivariana de Venezuela (Proyecto Fonacit Numero <u>2012000099</u>). El Servidor est&aacute; ubicado en el Centro de Simulaci&oacute;n y Modelos, 
CESIMO, de la Facultad de Ingenier&iacute;a, de la Universidad de Los Andes, en M&eacute;rida, Venezuela</p>
<p>Entre los servicios que presta este servidor se encuentran:</p>
<dl>
	<dt><b>InMemorian</b> : Ingeniería Linguística de la Memoria
	Cultural Andina</dt><dd>
	- <a href="./inmemorian/index.html">http://nux.ula.ve/inmemorian/</a>
	<b>Diccionario Electrónico de Ecocultura del Páramo Andino de
	Mérida.</b></dd><dd>
	- <a href="./inmemorian/miscelanea.html">http://nux.ula.ve/inmemorian/miscelanea.html</a>
	 Diccionario Electrónico de Ecocultura del Páramo Andino de
	Mérida. &Aacute;mbito: <b>Misceláneas</b></dd><dd>
	- <a href="./inmemorian/salud.html">http://nux.ula.ve/inmemorian/salud.html</a>
	 Diccionario Electrónico de Ecocultura del Páramo Andino de
	Mérida. &Aacute;mbito: <b>Salud</b></dd><dd>
	- <a href="./inmemorian/magia.html">http://nux.ula.ve/inmemorian/magia.html</a>
	 Diccionario Electrónico de Ecocultura del Páramo Andino de
	Mérida. &Aacute;mbito: <b>Magia y Religión</b></dd><dd>
	- <a href="./inmemorian/gastronomia.html">http://nux.ula.ve/inmemorian/gastronomia.html</a>
	 Diccionario Electrónico de Ecocultura del Páramo Andino de
	Mérida. &Aacute;mbito: <b>Gastronomía</b></dd><dd>
	- <a href="./inmemorian/florafauna.html">http://nux.ula.ve/inmemorian/florafauna.html</a>
	 Diccionario Electrónico de Ecocultura del Páramo Andino de
	Mérida. &Aacute;mbito: <b>Flora y Fauna</b></dd><dd>
	- <a href="./inmemorian/costumbres.html">http://nux.ula.ve/inmemorian/costumbres.html</a>
	 Diccionario Electrónico de Ecocultura del Páramo Andino de
	Mérida. &Aacute;mbito: <b>Costumbres</b></dd><dd>
	- <a href="./inmemorian/telares.html">http://nux.ula.ve/inmemorian/telares.html</a>
	 Diccionario Electrónico de Ecocultura del Páramo Andino de
	Mérida. &Aacute;mbito: <b>Telares y Tejidos</b></dd><dd>
	- <a href="./inmemorian/herramientas.html">http://nux.ula.ve/inmemorian/herramientas.html</a>
	 Diccionario Electrónico de Ecocultura del Páramo Andino de
	Mérida. &Aacute;mbito: <b>Herramientas</b></dd><dd>
	- <a href="./inmemorian/xml/">http://nux.ula.ve/inmemorian/xml/</a>
	 Corpus de muestras orales del lenguaje hablado en el páramo
	andino, transcritas y anotadas. 
	</dd><dd>
	- <a href="http://nux.ula.ve/inmemorian/DIRECTORIO_AUDIOS_VIDEO_INMEMORIAN/">http://nux.ula.ve/inmemorian/DIRECTORIO_AUDIOS_VIDEO_INMEMORIAN/</a>
	Archivos originales con muestras en audio y video del lenguaje
	hablado en el páramo andino merideño. 
	</dd><dd>
	- <a href="http://nux.ula.ve/wordpress/">http://nux.ula.ve/wordpress/</a>
	Bitácora del Proyecto InMemoriAn  (Pronto)</dd><dd>
	- <a href="http://nux.ula.ve/ceaweb/">http://nux.ula.ve/ceaweb/</a>
	Catálogo Electrónico del Repositorio de Publicaciones Andinas
	(Pronto)</dd><dd>
	- <a href="http://nux.ula.ve/inmemorian/primera-version/">http://nux.ula.ve/inmemorian/primera-version/</a>
	 Primera versión del diccionario electrónico y del corpus anotado.
		</dd><dt>
	<br/>

	</dt><dt>
	<b>Mathematica: Un juego para aprender matemáticas (código base)</b></dt><dd>
	- <a href="http://nux.ula.ve/mathematica/">http://nux.ula.ve/mathematica/</a>
	ULAnix Mathematica </b>
	</dd><dt>
	<br/>

	</dt><dt>
	<b>Propuestas </b><b>Comunitarias</b> 
	</dt><dd>
	- <a href="http://nux.ula.ve/propuesta/">http://nux.ula.ve/propuesta/</a>
	 Propuestas  comunitarias</dd><dd>
	- <a href="http://nux.ula.ve/abiertos/">http://nux.ula.ve/abiertos/</a>
	 Colección de archivos de audio, video y otros usados en
	actividades académicas y abiertos al público. 
	</dd><dd>
	- <a href="http://nux.ula.ve/audios/">http://nux.ula.ve/audios/</a> 
	Colección de audios grabados en actividades académicas
	universitarias. 
	</dd><dd>
	- <a href="http://nux.ula.ve/seminarios/">http://nux.ula.ve/seminarios/</a>
	Colección de archivos de seminarios</dd><dd>
	- <a href="http://nux.ula.ve/documentos/">http://nux.ula.ve/documentos/</a>
	Colección de documentos abiertos</dd><dd>
	- <a href="http://nux.ula.ve/manuales/">http://nux.ula.ve/manuales/</a>
	Colección de manuales técnicos libres</dd><dd>
	<br/>

	</dd><dt>
	<b>Servicio Comunitario Ulanux</b> 
	</dt><dd>
	- <a href="http://nux.ula.ve/ulanix/">http://nux.ula.ve/ulanix/</a> 
	Proyectos de Servicio Comunitario en ULAnux/ULAnix.  
	</dd><dd>
	- <a href="https://launchpad.net/%7Edavidhdz/+archive/ulanix">https://launchpad.net/~davidhdz/+archive/ulanix</a>
	 Paquetes de Software para ULAnux</dd><dd>
	- <a href="http://nux.ula.ve/canaima/">http://nux.ula.ve/canaima/</a>
	 Proyecto de Servicio Comunitario para las Canaimitas. 
	</dd><dd>
	<br/>

	</dd></dl>
<p>
Todo el material electrónico contenido en este repositorio ha sido
liberado con una licencia CC-BY-NC-SA a menos que se diga
explícitamente lo contrario. 
</p>
<p><font color="#ffffff">
 
   </div>
   <!--end holder--> 
  </div>
  <!--end container-->

   <!--start footer-->
   <footer>
      <div id="FooterOne">© 2016 (CC-BY) Diccionario InMemorian: Proyecto 2012000099. FONACIT, ULA, Venezuela</div>
         <div id="FooterTwo">this design is based on (©2011) Minimalist by <a href="http://www.marijazaric.com">marija zaric - creative simplicity</a> </div> 
	 <div id="FooterThree"><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/ve/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/3.0/ve/88x31.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/ve/">Licencia Creative Commons Atribución-NoComercial-CompartirIgual 3.0 Venezuela</a></div>
   </footer>
   <!--end footer-->
   </div>
   <!--end bg-->
   <!-- Free template distributed by http://freehtml5templates.com -->
  </body>
</html>
