	</div>
	<!--end holder-->
   <!--start holder-->
   <!--end holder-->
   </div>
   <!--end container-->
   <!--start footer-->
   <footer>
      <div id="FooterOne">© 2016 (CC-BY) Diccionario InMemorian: Proyecto 2012000099. FONACIT, ULA, Venezuela</div>
         <div id="FooterTwo">this design is based on (©2011) Minimalist by <a href="http://www.marijazaric.com">marija zaric - creative simplicity</a> </div> 
	 <div id="FooterThree"><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/ve/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/3.0/ve/88x31.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/ve/">Licencia Creative Commons Atribución-NoComercial-CompartirIgual 3.0 Venezuela</a></div>
   </footer>
   <!--end footer-->
   </div>
   <!--end bg-->
   <!-- Free template distributed by http://freehtml5templates.com -->
  </body>
</html>
