<!doctype html>
<html lang="es">
<head>
<meta charset="UTF-8">
<title>InMemoriAN: Diccionario de Ecocultura del P&aacute;ramo Andino de M&eacute;rida</title>
<meta name="description" content="Version 3.0 del diccionario generado autom&aacute;ticamente">
<meta name="author" content="Glosarizador InMemoriAN">
<link rel="icon" href="media/favicon.gif" type="image/x-icon"/>
 <!--[if lt IE 9]>
 <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
<link rel="shortcut icon" href="media/favicon.gif" type="image/x-icon"/> 
<link rel="stylesheet" type="text/css" href="css/styles.css"/>
</head>
<body>
   <div class="bg">
    <!--start container-->
    <div id="container">
    <!--start header-->
    <header>
      <!--start logo-->
      <a href="#" id="logo"><img src="media/logo.png" width="220" height="180" alt="logo"/></a>    
      <!--end logo-->
      <!--start menu-->
      <nav>
         <ul>
         <li><h3>InMemoriAn: Ingenier&iacute;a Lingu&iacute;stica de la Memoria Cultural Andina</h3></li>
         <li><h3>Proyecto FONACIT 2012000099 Venezuela 2013-2016</h3></li>
         <li><h1>Diccionario de Ecocultura del P&aacute;ramo Andino de M&eacute;rida</h1></li> 
	 </ul>
         <ul>
         <li><a href="index.html" class="current">Principal</a></li>
         <li><a href="proyecto.html">Sobre el Proyecto</a></li>
         <li><a href="Creative Commons Legal Code.html">Licencia</a></li>
         <!--
     	   <li><a href="#">Services</a></li>
     	   <li><a href="#">Portfolio</a></li>
         <li><a href="#">News</a></li>
         -->
         <li><a href="creditos.html">Contactos</a></li>
         </ul>   
      </nav>
  	   <!--end menu-->
      <!--end header-->
	</header>
<!--start holder-->
   <div class="holder_content">
      <section class="group1">
      <h1>Indice del Diccionario</h1> 
      <p>Este diccionario es una selecci&oacute;n autom&aacute;tica de textos a partir del corpus generado por un equipo de transcriptores de una serie de entrevistas a vecinos del p&aacute;ramo andino meride&ntilde;o</p>
      <p>Para consultarlo puede buscar palabras o frases (Ctrl-F) en esta p&aacute;gina y luego seguir el enlace que resulte destacado. Entonces, siga el enlace para leer la definici&oacute;n en una  p&aacute;gina separada desde donde podr&aacute; imprimir o guardar</p>
      <p>El diccionario cuenta con un conjunto de &iacute;ndices por &aacute;reas tem&aacute;ticas que se indican a continuaci&oacute;n.</p>
<dl>
	<dt>
    <dd>- <a href="miscelanea.html">http://nux.ula.ve/inmemorian/miscelanea.html</a>
	  &Aacute;mbito: <b>Misceláneas</b></dd><dd>
	- <a href="salud.html">http://nux.ula.ve/inmemorian/salud.html</a>
	  &Aacute;mbito: <b>Salud</b></dd><dd>
	- <a href="magia.html">http://nux.ula.ve/inmemorian/magia.html</a>
	  &Aacute;mbito: <b>Magia y Religión</b></dd><dd>
	- <a href="gastronomia.html">http://nux.ula.ve/inmemorian/gastronomia.html</a>
	  &Aacute;mbito: <b>Gastronomía</b></dd><dd>
	- <a href="florafauna.html">http://nux.ula.ve/inmemorian/florafauna.html</a>
	  &Aacute;mbito: <b>Flora y Fauna</b></dd><dd>
	- <a href="costumbres.html">http://nux.ula.ve/inmemorian/costumbres.html</a>
	  &Aacute;mbito: <b>Costumbres</b></dd><dd>
	- <a href="telares.html">http://nux.ula.ve/inmemorian/telares.html</a>
	  &Aacute;mbito: <b>Telares y Tejidos</b></dd><dd>
	- <a href="herramientas.html">http://nux.ula.ve/inmemorian/herramientas.html</a>
	  &Aacute;mbito: <b>Herramientas</b></dd><dd>
	- <a href="./xml/">http://nux.ula.ve/inmemorian/xml/</a>
	 Corpus de muestras orales del lenguaje hablado en el páramo
	andino, transcritas y anotadas. 
	</dd><dd>
	- <a href="./DIRECTORIO_AUDIOS_VIDEO_INMEMORIAN/">http://nux.ula.ve/inmemorian/DIRECTORIO_AUDIOS_VIDEO_INMEMORIAN/</a>
	Archivos originales con muestras en audio y video del lenguaje
	hablado en el páramo andino merideño. 
	</dd><dd>
	- <a href="http://nux.ula.ve/wordpress/">http://nux.ula.ve/wordpress/</a>
	Bitácora del Proyecto InMemoriAn  (Pronto)</dd><dd>
	- <a href="http://nux.ula.ve/ceaweb/">http://nux.ula.ve/ceaweb/</a>
	Catálogo Electrónico del Repositorio de Publicaciones Andinas
	(Pronto)</dd><dd>
	- <a href="http://nux.ula.ve/inmemorian/primera-version/">http://nux.ula.ve/inmemorian/primera-version/</a>
	 Primera versión del diccionario electrónico y del corpus anotado.
		</dd><dd>
	- <a href="./src/">http://nux.ula.ve/inmemorian/src/</a>
	 Códigos fuentes del glosarizador-diccionarizador InMemoriAN. 
		</dd>
	<dt>	
</dl>
<br/> 
      </group1>
      </section>
<!-- http://nux.ula.ve/inmemorian/ -->



