<!doctype html>
<html lang="es">
<head>
<meta charset="UTF-8">
<title>InMemoriAN: Diccionario de Ecocultura del P&aacute;ramo Andino de M&eacute;rida - &Aacute;mbito Magia y Religi&oacute;n</title>
<meta name="description" content="Version 3.0 del diccionario generado autom&aacute;ticamente">
<meta name="author" content="Glosarizador InMemoriAN">
<link rel="icon" href="media/favicon.gif" type="image/x-icon"/>
 <!--[if lt IE 9]>
 <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
<link rel="shortcut icon" href="media/favicon.gif" type="image/x-icon"/> 
<link rel="stylesheet" type="text/css" href="css/styles.css"/>
</head>
<body>
   <div class="bg">
    <!--start container-->
    <div id="container">
    <!--start header-->
    <header>
      <!--start logo-->
      <a href="#" id="logo"><img src="media/magia_religion.png" width="220" height="180" alt="logo"/></a>    
      <!--end logo-->
      <!--start menu-->
      <nav>
         <ul>
         <li><h3>InMemoriAn: Ingenier&iacute;a Lingu&iacute;stica de la Memoria Cultural Andina: Magia y Religi&oacute;n</h3></li>
         <li><h3>Proyecto FONACIT 2012000099 Venezuela 2013-2016</h3></li>
         <li><h1>Diccionario de Ecocultura del P&aacute;ramo Andino de M&eacute;rida</h1></li> 
	 </ul>
         <ul>
         <li><a href="index.html" class="current">Principal</a></li>
         <li><a href="proyecto.html">Sobre el Proyecto</a></li>
         <li><a href="Creative Commons Legal Code.html">Licencia</a></li>
         <!--
     	   <li><a href="#">Services</a></li>
     	   <li><a href="#">Portfolio</a></li>
         <li><a href="#">News</a></li>
         -->
         <li><a href="creditos.html">Contactos</a></li>
         </ul>   
      </nav>
  	   <!--end menu-->
      <!--end header-->
	</header>
  <div class="holder_content">
      <section class="group1">
   <h1>Indice del Diccionario: &Aacute;mbito Magia y Religi&oacute;n</h1> 
      <group1>
      <p>Este diccionario es una selecci&oacute;n autom&aacute;tica de textos a partir del corpus generado por un equipo de transcriptores de una serie de entrevistas a vecinos del p&aacute;ramo andino meride&ntilde;o</p>
      <p>Para consultarlo puede buscar palabras o frases (Ctrl-F) en esta p&aacute;gina y luego seguir el enlace que resulte destacado. Entonces, siga el enlace para leer la definici&oacute;n en una  p&aacute;gina separada desde donde podr&aacute; imprimir o guardar</p> 
      </group1>
   </section>
